on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip extension
        run: zip -r chrome.zip chrome

      - name: Check zip
        run: ls -la

      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      # - name: Build
      #   run: |
      #     npm ci
      #     npm run build
      # - name: Upload & release
      #   uses: mnao305/chrome-extension-upload@1.1.1
      #   with:
      #     file-path: dist/file.zip
      #     extension-id: hogefuga(extension id)
      #     client-id: ${{ secrets.CLIENT_ID }}
      #     client-secret: ${{ secrets.CLIENT_SECRET }}
      #     refresh-token: ${{ secrets.REFRESH_TOKEN }}
